# Permalinks
permalink:           pretty

# Setup
title:               Andrew Walsh
tagline:             Data's Fear
url:                 http://awalsh00.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrew Walsh
  url:               https://awalsh00.github.io
  email:             awalsh0000@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/awalsh00

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
